name: Push File

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: DanukaPraneeth/pr-library@v1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'folder1'
        destination_repo: 'DanukaPraneeth/test-target-repo'
        destination_folder: ''
        destination_base_branch: 'master'
        destination_head_branch: 'master'
        user_email: 'a.g.danuka@gmail.com'
        user_name: 'DanukaPraneeth'
        pull_request_reviewers: 'DanukaPraneeth'
