name: Continuous Integration

on: push
    
jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File
        
        steps:
        - name: Checkout main-project
          uses: actions/checkout@v2
          with:
            path: ./test-source-repo       

        - name: Come back
          run: |
            cd ..
            ls -ltr
            pwd


        - name: Checkout secondary-project
          uses: actions/checkout@v2
          with: 
            repository: DanukaPraneeth/test-target-repo
            token: ${{ secrets.MY_TOKEN || github.token }}
            path: ./test-target-repo

        - name: Copy file
          run: |
            ls -ltr
            ls -ltr ../
            pwd
            cp -r ./test-source-repo/* ./test-target-repo/
            

        - name: Push To Repo2
          run: |
            ls
            pwd
            cd ./test-target-repo
            git add .
            git config user.name "DanukaPraneeth"
            git config user.email “danuka@gmail.com”
            git remote set-url origin https://DanukaPraneeth:${{ secrets.XX || github.token }}@github.com/DanukaPraneeth/test-target-repo.git
            git checkout -b update-form
            git commit -am "Update files"
            git push --set-upstream origin update-form
            
            
        - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "main" 
            source_branch: "update-form"
            
