name: Continuous Integration

on: push
    
jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File
        
        steps:
        - name: Check the downloaded repo status
          run: |
            pwd
            ls -ltr
            rm -rf *
            ls -ltr
        
        - name: Checkout main-project
          uses: actions/checkout@v2
          with:
            path: ./test-source-repo       

        - name: Check the downloaded repo status
          run: |
            ls -ltr
            pwd


        - name: Checkout secondary-project
          uses: actions/checkout@v2
          with: 
            repository: DanukaPraneeth/test-target-repo
            token: ${{ secrets.MY_TOKEN || github.token }}
            path: ./test-target-repo

        - name: Copy file
          run: |
            ls -ltr
            pwd
            echo "Before coping the file"
            ls -ltr ./test-target-repo/

            FILE=./test-source-repo/main_old.yaml
            FILE2=./test-source-repo/main_new.yaml
            if [ -f "$FILE" ]; 
            then
              echo "Copying $FILE"
              cp -R $FILE ./test-target-repo/
            fi

            if [ -f "$FILE2" ];
            then
              echo "Copying $FILE2"
              cp -R $FILE2 ./test-target-repo/
            fi

            echo "After coping the file"
            ls -ltr ./test-target-repo/


        - name: Push To Repo2
          run: |
            ls
            pwd
            cd ./test-target-repo
            pwd
            TIME_NOW=$(date +%s)
            BRANCH_NAME="update-from-${TIME_NOW}"
            git add .
            git config user.name "Danuka"
            git config user.email "danuka@gmail.com"
            echo "Below is my new branch name with the time stamp as the unique string"
            git checkout -b $BRANCH_NAME
            git commit -am "Update files"
            git push --set-upstream origin $BRANCH_NAME
            
            
        - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "main" 
            source_branch: "update-form"
            
